name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        # env: 
        #   DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cell_tp_pred:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f cell_tp_pred-container || true
    
      - name: Run Docker Container
        # env: 
        #   DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d -p 8001:8001 --name cell_tp_pred-container ${{ secrets.DOCKER_USERNAME }}/cell_tp_pred:latest

