name: CI Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train and save pipeline
      run: python cell_TP_pred_model/train_pipeline.py
    - uses: actions/upload-artifact@v4
      with:
        name: my-trained-pipeline
        path: cell_TP_pred_model/trained_models/*.json
        retention-days: 1

  build:
    needs: [train]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v4
      with:
        name: my-trained-pipeline
        path: cell_TP_pred_model/trained_models
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v4
      with:
        name: my-build-package
        path: dist/*.whl
        retention-days: 1

  push-image:
    needs: [train, build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v4
      with:
        name: my-build-package
        path: cell_TP_pred_api

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secret for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secret for Docker Hub Access Token

    - name: Build the Docker image for Fastapi app
      run: docker build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/cell_tp_pred:latest

    - name: Push the Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cell_tp_pred

    - name: Logout to Docker hub
      run: docker logout
